### ISSUE TITLE
saving labels is broken

### ISSUE THREAD

**Issue by lwthatcher** [lwthatcher/stickers#60]
# Saving Labels Not Working
It appears in our tests earlier with @coutnib the labels she created were **_not_** saved to the server...

I attempted to duplicate this issue and my labels were also not saved to the server. I did get an error logged to the console saying my request had failed, and a corresponding error in the `tcm` server was also logged.

## Server Error
```
[2018-09-24 23:09:52,999] ERROR in app: Exception on /api/save/labels [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/users/home/lthatch1/repos/tcm/tcm/server/api_server.py", line 75, in save_labels
    datum = ws.add_labels(path, **kwargs)
  File "/users/home/lthatch1/repos/tcm/tcm/workspace/workspace.py", line 185, in add_labels
    if orig_file:
  File "/users/home/lthatch1/repos/tcm/tcm/workspace/workspace.py", line 287, in _labels_datum
    # extract variables from kwargs
  File "/users/home/lthatch1/repos/tcm/tcm/workspace/inferencers.py", line 214, in infer_event_map
    events = self.infer_events(events) or []
  File "/users/home/lthatch1/repos/tcm/tcm/workspace/inferencers.py", line 193, in infer_events
    lbls, counts = self._lbls_and_counts()
  File "/users/home/lthatch1/repos/tcm/tcm/workspace/inferencers.py", line 245, in _lbls_and_counts
    t = lbl['type']
KeyError: 'type'
127.0.0.1 - - [24/Sep/2018 23:09:53] "POST /api/save/labels HTTP/1.1" 500 -

```

**Comment by lwthatcher** [comment]
It looks like this is an issue with inconsistent formatting between the old version of vat and now. This is probably the same cause for issue #48.

**Comment by lwthatcher** [comment]
## Update:
I've tried several other scenarios where I _was_ able to save the labels from stickers, it seems the case that I got to fail was when I tried to save labels where the null label was the only label that existed.

**Comment by lwthatcher** [comment]
## Update
Upon closer experimentation I was _also_ able to get it to fail when offering a non-empty set of labels for a label scheme if that scheme had _previously_ attempted to save an empty event-map but failed.

In such cases the **file** was saved, but the corresponding datum in the `.workspace.json` file was not properly created or saved. The server in turn returns an error saying the file already exists.

### Server Error
```
[2018-09-25 12:47:44,262] ERROR in app: Exception on /api/save/labels [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/users/home/lthatch1/repos/tcm/tcm/server/api_server.py", line 68, in save_labels
    path = ws.labels_file(name)
  File "/users/home/lthatch1/repos/tcm/tcm/workspace/workspace.py", line 349, in labels_file
    raise ValueError('Path already exists: {}'.format(path))
ValueError: Path already exists: /users/data/workspaces/cleaning/A/null-only.labels.json
127.0.0.1 - - [25/Sep/2018 12:47:44] "POST /api/save/labels HTTP/1.1" 500 -
```

**Comment by lwthatcher** [comment]
## Update
This issue is mostly remedied with the _tcm_ `3.4.2` patch release.
If you try to save a file with only null labels from _stickers_ you will get weird results for the corresponding labels datum `event-map` field in the `.workspace.json` file -- however it will **not** cause a server error and fail to save the data.

With that being the case, this issue is mostly resolved, as it no longer affects the user interface experience. I am hence closing this issue, but still leaving [tcm issue #23](https://github.com/byuhci/tcm/issues/23) open until the entire problem is resolved.
