### ISSUE TITLE
Courtni's Current Errors

### ISSUE THREAD

**Issue by coutnib** [lwthatcher/stickers#63]
This is the output I'm getting now when I try to run ng serve:

```
cowudder@recall:~/TCMStickers/stickers/stickers-master$ ng serve
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

Your global Angular CLI version (1.0.0-beta.28.3) is greater than your local
version (1.0.0-beta.22-1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

** NG Live Development Server is running on http://localhost:4200. **
Hash: 4be5b94251ccb75d9a2c                                                               
Time: 8051ms
chunk    {0} main.bundle.js, main.bundle.map (main) 3.49 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 9.85 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.63 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.component.ts (86,35): Property 'paramMap' does not exist on type 'ActivatedRouteSnapshot'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.component.ts (87,35): Property 'paramMap' does not exist on type 'ActivatedRouteSnapshot'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.component.ts (139,29): Property 'paramMap' does not exist on type 'ActivatedRouteSnapshot'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.component.ts (140,52): Property 'paramMap' does not exist on type 'ActivatedRouteSnapshot'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.component.ts (167,16): Type 'string' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.component.ts (299,30): Property 'entries' does not exist on type 'ObjectConstructor'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.component.ts (342,16): Type 'string' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/data-loader.service.ts (2,53): Cannot find module '@angular/common/http'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/data-loader.service.ts (4,23): Cannot find module 'tfjs-npy'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/data-loader.service.ts (5,21): Cannot find module '@tensorflow/tfjs-core'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/data-loader.service.ts (6,21): Cannot find module 'd3'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/info/workspace-info.ts (38,23): Property 'entries' does not exist on type 'ObjectConstructor'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/info/workspace-info.ts (42,23): Property 'entries' does not exist on type 'ObjectConstructor'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/info/workspace-info.ts (46,23): Property 'entries' does not exist on type 'ObjectConstructor'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/sensors/sensor.ts (107,27): Type 'string' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/sensors/sensor.ts (114,20): Type 'string' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/dataset.ts (2,21): Cannot find module '@tensorflow/tfjs-core'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/dataset.ts (3,23): Cannot find module 'mathjs'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/dataset.ts (62,95): Property 'includes' does not exist on type 'number[]'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/settings/settings.service.ts (3,28): Cannot find module '@angular/common/http'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/event-types/colorer.ts (3,21): Cannot find module 'd3'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/event-types/colorer.ts (85,23): Property 'entries' does not exist on type 'ObjectConstructor'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/labels-loader.service.ts (3,28): Cannot find module '@angular/common/http'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/event-types/types-toolbox.component.ts (6,28): Cannot find module '@ng-bootstrap/ng-bootstrap'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/event-types/types-toolbox.component.ts (7,21): Cannot find module 'd3'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/event-types/types-toolbox.component.ts (43,37): Property 'firstChange' does not exist on type 'SimpleChange'. Did you mean 'isFirstChange'?

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/sensors/sensors-toolbox.component.ts (28,24): Type 'string' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/labelstreams/labelstreams-toolbox.component.ts (4,41): Cannot find module '@ng-bootstrap/ng-bootstrap'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/saver/saver.service.ts (2,28): Cannot find module '@angular/common/http'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/databar.component.ts (15,25): Cannot find module 'spin.js'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/databar.component.ts (16,44): Cannot find module 'd3fc-sample'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/databar.component.ts (143,33): Property 'firstChange' does not exist on type 'SimpleChange'. Did you mean 'isFirstChange'?

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/databar.component.ts (144,37): Property 'firstChange' does not exist on type 'SimpleChange'. Did you mean 'isFirstChange'?

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/databar.component.ts (145,31): Property 'firstChange' does not exist on type 'SimpleChange'. Did you mean 'isFirstChange'?

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/databar.component.ts (146,25): Property 'firstChange' does not exist on type 'SimpleChange'. Did you mean 'isFirstChange'?

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/labeller/labeller.ts (3,21): Cannot find module 'd3'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/drawer/drawer.ts (13,21): Cannot find module 'd3'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/drawer/time-format.ts (7,71): Property 'padStart' does not exist on type 'string'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/drawer/time-format.ts (9,37): Property 'padStart' does not exist on type 'string'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/drawer/layers.ts (88,24): Property 'values' does not exist on type 'ObjectConstructor'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/energy/energy-wells.ts (8,23): Cannot find module 'mathjs'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/energy/energy-wells.ts (9,21): Cannot find module 'd3'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/drawer/behaviors/highlight.ts (2,21): Cannot find module 'd3'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/drawer/behaviors/drag.ts (2,21): Cannot find module 'd3'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/drawer/behaviors/pour.ts (2,21): Cannot find module 'd3'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/drawer/behaviors/pour.ts (3,28): Cannot find module 'd3-force-surface'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/drawer/behaviors/mouse.ts (2,21): Cannot find module 'd3'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/drawer/behaviors/mouse.ts (29,28): Property 'includes' does not exist on type 'string[]'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/databar/drawer/behaviors/zoom.ts (2,21): Cannot find module 'd3'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/video/video-tracker.ts (2,23): Cannot find module 'videogular2/core'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/video/video.component.ts (5,23): Cannot find module 'videogular2/core'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/video/video.component.ts (220,59): Property 'includes' does not exist on type 'string[]'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/video/video.component.ts (221,28): Property 'includes' does not exist on type 'string[]'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/energy/energy-well-toolbox.component.ts (3,28): Cannot find module '@ng-bootstrap/ng-bootstrap'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/workspace-resolver.service.ts (69,19): Type 'Set<string>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/data-loader/workspace-loader.service.ts (3,28): Cannot find module '@angular/common/http'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.module.ts (5,27): Cannot find module '@ng-bootstrap/ng-bootstrap'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.module.ts (8,48): Cannot find module '@angular/material'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.module.ts (9,36): Cannot find module '@angular/material/expansion'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.module.ts (10,31): Cannot find module '@angular/material/list'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.module.ts (11,31): Cannot find module '@angular/material/menu'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.module.ts (12,33): Cannot find module '@angular/material/button'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.module.ts (13,41): Cannot find module '@angular/platform-browser/animations'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.module.ts (14,28): Cannot find module 'videogular2/core'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.module.ts (15,32): Cannot find module 'videogular2/controls'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.module.ts (16,35): Cannot find module 'videogular2/overlay-play'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/dataview.module.ts (17,33): Cannot find module 'videogular2/buffering'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/labelstreams/popover/new-labelstream-popover.component.ts (24,55): Property 'includes' does not exist on type 'string[]'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/dataview/labelstreams/popover/edit-labelstream-popover.component.ts (25,55): Property 'includes' does not exist on type 'string[]'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/home/home.module.ts (7,31): Cannot find module '@angular/material/card'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/home/home.module.ts (8,31): Cannot find module '@angular/material/menu'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/home/home.module.ts (9,33): Cannot find module '@angular/material/button'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/home/home.module.ts (10,34): Cannot find module '@angular/material/divider'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/home/home.module.ts (11,36): Cannot find module '@angular/material/expansion'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/home/home.module.ts (13,46): Cannot find module '@angular/material/icon'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/home/home.module.ts (15,27): Cannot find module '@ng-bootstrap/ng-bootstrap'.

ERROR in /users/researcher/cowudder/TCMStickers/stickers/stickers-master/src/app/home/home.module.ts (16,41): Cannot find module '@angular/platform-browser/animations'.
webpack: Failed to compile.
```

**Comment by coutnib** [comment]
I'm not sure if this is better or worse, but this is what I'm getting now:

cowudder@recall:~/TCMStickers/stickers/stickers-master$ ng serve
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

Your global Angular CLI version (1.0.0-beta.28.3) is greater than your local
version (1.0.0-beta.22-1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

** NG Live Development Server is running on http://localhost:4200. **
  0% compilingCannot read property 'thisCompilation' of undefined
TypeError: Cannot read property 'thisCompilation' of undefined
    at NodeTemplatePlugin.apply (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack/lib/node/NodeTemplatePlugin.js:19:18)
    at Compiler.apply (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:375:16)
    at Object.compileTemplate (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/html-webpack-plugin/lib/compiler.js:48:17)
    at Compiler.<anonymous> (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/html-webpack-plugin/index.js:47:40)
    at Compiler.applyPluginsParallel (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:293:14)
    at Compiler.<anonymous> (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:463:8)
    at Compiler.applyPluginsAsyncSeries (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:195:46)
    at Compiler.compile (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:456:7)
    at Watching.<anonymous> (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:46:17)
    at next (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.compilerInvalid (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack-dev-middleware/lib/Shared.js:161:5)
    at next (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:204:14)
    at Compiler.<anonymous> (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/CachePlugin.js:31:4)
    at Compiler.applyPluginsAsyncSeries (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:206:13)
    at Watching._go (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:44:16)
    at Watching.<anonymous> (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:36:8)
    at Compiler.readRecords (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:367:10)
    at new Watching (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:33:16)
    at Compiler.watch (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:204:17)
    at Object.startWatch (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack-dev-middleware/lib/Shared.js:176:29)
    at Shared (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack-dev-middleware/lib/Shared.js:238:8)
    at module.exports (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack-dev-middleware/middleware.js:22:15)
    at new Server (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack-dev-server/lib/Server.js:43:20)
    at Class.run (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/tasks/serve-webpack.js:85:22)
    at /users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/commands/serve.js:102:26
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
cowudder@recall:~/TCMStickers/stickers/stickers-master$

**Comment by coutnib** [comment]
Okay, I ran the command you gave me, but now I am getting the same error with some other stuff. I found a post on stackexchange that says I need to go in and manually update some files in node_moduels, so I'm going to try that and hope I don't break anything else. Anyway, here is the output I'm getting now: 

cowudder@recall:~/TCMStickers/stickers/stickers-master$ ng serve
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
** NG Live Development Server is running on http://localhost:4200. **
  0% compilingCannot read property 'thisCompilation' of undefined
TypeError: Cannot read property 'thisCompilation' of undefined
    at NodeTemplatePlugin.apply (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack/lib/node/NodeTemplatePlugin.js:19:18)
    at Compiler.apply (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:375:16)
    at Object.compileTemplate (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/html-webpack-plugin/lib/compiler.js:48:17)
    at Compiler.<anonymous> (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/html-webpack-plugin/index.js:47:40)
    at Compiler.applyPluginsParallel (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:293:14)
    at /users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:469:8
    at Compiler.applyPluginsAsyncSeries (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:195:46)
    at Compiler.compile (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:462:7)
    at /users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:45:17
    at next (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.compilerInvalid (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack-dev-middleware/lib/Shared.js:161:5)
    at next (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:204:14)
    at Compiler.compiler.plugin (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/CachePlugin.js:32:5)
    at Compiler.applyPluginsAsyncSeries (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/tapable/lib/Tapable.js:206:13)
    at Watching._go (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:43:16)
    at Watching.<anonymous> (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:34:8)
    at Compiler.readRecords (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:372:10)
    at new Watching (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:31:16)
    at Compiler.watch (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:203:17)
    at Object.startWatch (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack-dev-middleware/lib/Shared.js:176:29)
    at Shared (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack-dev-middleware/lib/Shared.js:238:8)
    at module.exports (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack-dev-middleware/middleware.js:22:15)
    at new Server (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/webpack-dev-server/lib/Server.js:53:20)
    at Class.run (/users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/tasks/serve.js:107:22)
    at /users/researcher/cowudder/TCMStickers/stickers/stickers-master/node_modules/angular-cli/commands/serve.run.js:22:22
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
cowudder@recall:~/TCMStickers/stickers/stickers-master$
